import { BuildingDefinition } from "@shared/interface/building.interface";

export const BUILDINGS: BuildingDefinition[] = [
	{
		id: "core",
		name: "Core",
		category: "core",
		model: "Core",
		size: { x: 5, y: 5 },
		maxTier: 5,
		description: "Il cuore della tua base. Ogni upgrade sblocca nuove strutture e aumenti dimensionali.",
		tiers: {
			1: { cost: 0, buildTime: 0, hitpoints: 1000 },
			2: { cost: 10000, buildTime: 1200, hitpoints: 3000, unlocksAtLevel: 2 },
			3: { cost: 50000, buildTime: 3600, hitpoints: 6000, unlocksAtLevel: 3 },
			4: { cost: 150000, buildTime: 7200, hitpoints: 12000, unlocksAtLevel: 4 },
			5: { cost: 500000, buildTime: 14400, hitpoints: 25000, unlocksAtLevel: 5 },
		},
	},
	{
		id: "gold_mine",
		name: "Miniera d'Oro",
		category: "resource",
		model: "GoldMine",
		size: { x: 1, y: 1 },
		maxTier: 6,
		description: "Estrae oro lentamente nel tempo. Essenziale per ogni upgrade.",
		tiers: {
			1: {
				cost: 500,
				buildTime: 60,
				hitpoints: 250,
				capacity: 1000,
				resource: { type: "gold", amount: 5, time: 10 },
				requiredTownHall: 1,
			},
			2: {
				cost: 2500,
				buildTime: 300,
				hitpoints: 400,
				capacity: 2500,
				resource: { type: "gold", amount: 10, time: 10 },
				requiredTownHall: 1,
			},
			3: {
				cost: 10000,
				buildTime: 1200,
				hitpoints: 750,
				capacity: 5000,
				resource: { type: "gold", amount: 20, time: 8 },
				requiredTownHall: 2,
				requirements: [{ id: "core", tier: 2 }],
			},
			4: {
				cost: 30000,
				buildTime: 2400,
				hitpoints: 1200,
				capacity: 10000,
				resource: { type: "gold", amount: 35, time: 7 },
				requiredTownHall: 3,
			},
			5: {
				cost: 75000,
				buildTime: 4800,
				hitpoints: 2000,
				capacity: 20000,
				resource: { type: "gold", amount: 60, time: 6 },
				requiredTownHall: 4,
				requirements: [{ id: "core", tier: 4 }],
			},
			6: {
				cost: 150000,
				buildTime: 9600,
				hitpoints: 3000,
				capacity: 50000,
				resource: { type: "gold", amount: 100, time: 5 },
				requiredTownHall: 5,
				requirements: [{ id: "core", tier: 5 }],
			},
		},
	},
	{
		id: "energy_well",
		name: "Pozzo Energetico",
		category: "resource",
		model: "EnergyWell",
		size: { x: 1, y: 1 },
		maxTier: 6,
		description: "Produce energia lentamente, fondamentale per difese e tecnologie.",
		tiers: {
			1: {
				cost: 1000,
				buildTime: 120,
				hitpoints: 300,
				capacity: 1000,
				resource: { type: "energy", amount: 3, time: 10 },
				requiredTownHall: 1,
			},
			2: {
				cost: 3000,
				buildTime: 360,
				hitpoints: 500,
				capacity: 2000,
				resource: { type: "energy", amount: 7, time: 10 },
				requiredTownHall: 2,
			},
			3: {
				cost: 8000,
				buildTime: 900,
				hitpoints: 800,
				capacity: 4000,
				resource: { type: "energy", amount: 15, time: 8 },
				requiredTownHall: 2,
				requirements: [{ id: "gold_mine", tier: 3 }],
			},
			4: {
				cost: 20000,
				buildTime: 1800,
				hitpoints: 1300,
				capacity: 8000,
				resource: { type: "energy", amount: 30, time: 8 },
				requiredTownHall: 3,
			},
			5: {
				cost: 50000,
				buildTime: 3600,
				hitpoints: 2000,
				capacity: 16000,
				resource: { type: "energy", amount: 50, time: 6 },
				requiredTownHall: 4,
				requirements: [
					{ id: "core", tier: 4 },
					{ id: "gold_mine", tier: 4 },
				],
			},
			6: {
				cost: 120000,
				buildTime: 7200,
				hitpoints: 3000,
				capacity: 32000,
				resource: { type: "energy", amount: 90, time: 5 },
				requiredTownHall: 5,
				requirements: [
					{ id: "core", tier: 5 },
					{ id: "gold_mine", tier: 6 },
				],
			},
		},
	},
];

export const CORE_REF = BUILDINGS.find((b) => b.id === "core")!;
